spring:

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8081/realms/kateringapp
          jwk-set-uri: http://keycloak:8081/realms/kateringapp/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/katering
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false