spring:

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8081/realms/kateringapp
          jwk-set-uri: http://localhost:8081/realms/kateringapp/protocol/openid-connect/certs

  h2:
    console:
      enabled: true # http://localhost:8080/h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG