spring:

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8081/realms/KateringApp
          jwk-set-uri: http://keycloak:8081/realms/KateringApp/protocol/openid-connect/certs

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never

logging:
  level:
    root: error

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false