name: Deploy Application

on:
  push:
      branches:
        - main  # lub inna gałąź, na którą chcesz wdrożyć
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Build Frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies for Angular
      run: |
        cd frontend
        npm install

    - name: Build Angular app
      run: |
        cd frontend
        npm run build --prod

    # Build Backend
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Maven
      run: |
        sudo apt update
        sudo apt install maven

    - name: Build Spring Boot app with Maven
      run: |
        cd backend
        mvn clean install -DskipTests

    # Build keycloak
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run Keycloak Docker container
      run: |
        docker run -d --name keycloak -p 8080:8080 jboss/keycloak

    # Deploy frontend
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # lub inna gałąź dla GitHub Pages
        folder: frontend/dist  # Ścieżka do folderu z zbudowanym front-endem
        token: ${{ secrets.GITHUB_TOKEN }}

    # Deploy backend
    - name: Build and run Spring Boot in Docker
      run: |
        docker build -t spring-backend ./backend
        docker run -d -p 8081:8080 spring-backend
